apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dxef
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-dxef@sha256:0a1b4d2b339c138d6d03e6dbf6cb1c78f59f2a73b6c34659773f9cf563b8bfe0
        name: my-nodejs
        resources: {}
status: {}
